### PR TITLE
GObject to GLib & python2 to python3 port

### LINKED ISSUE #9: Port from GObject to GLib

### LINKED ISSUE #10: PyGI warnings
````
PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, GObject, Gdk
/home/ayush/activities/locosugar/sprites.py:81: PyGIWarning: PangoCairo was imported without specifying a version first. 
Use gi.require_version('PangoCairo', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import Pango, PangoCairo
````

### PR DESCRIPTION
**Pull request by Saumya-Mishra9129**
Fixes #9, Fixes #10.
@ayushnawal @quozl kindly review it.

### CODE REVIEW

**Comment by chimosky** [comment]
6a683d8 and 2d64d52 seems to be duplicates of #8, you can close #8 if you intend to move your work here. It'll be great if the flake8 fixes were in a different PR as it makes review a bit difficult.

**Comment by Saumya-Mishra9129** [comment]
@chimosky as suggested by you, I will send a different Pull request for flake8 fixes and leaving it for GObject to GLib .

**Comment by Saumya-Mishra9129** [comment]
@chimosky Have a look please and tell me if further changes required with GObject to GLib port & with Python2 to Python3 port. Thanks.

**Comment by chimosky** [comment]
Could you separate the flake8 fixes from the port to `GLib`? 
You can do a rebase and drop that commit and make the changes for the port to `GLib` alone or you can also do a rebase and commit only the changes related to the port to `GLib`.

**Comment by Saumya-Mishra9129** [comment]
I am closing this pull request and will send a new one. Thanks

**Pull request closed without merging**
